spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/students/**
            
eureka:
  client:
    service-url:
      service-url:
      defaultZone: http://localhost:8761/eureka/  
  

